# Generated by Django 5.0.6 on 2024-06-08 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата производства продукта"
            ),
        ),
    ]
