# Generated by Django 5.0.6 on 2024-07-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_description_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price_per_purchase",
            new_name="price",
        ),
    ]
